# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(450, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lineEditPertama = QtWidgets.QLineEdit(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.lineEditPertama.setFont(font)
        self.lineEditPertama.setObjectName("lineEditPertama")
        self.horizontalLayout.addWidget(self.lineEditPertama)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.lineEditKedua = QtWidgets.QLineEdit(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.lineEditKedua.setFont(font)
        self.lineEditKedua.setObjectName("lineEditKedua")
        self.horizontalLayout_2.addWidget(self.lineEditKedua)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pb_Tambah = QtWidgets.QPushButton(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.pb_Tambah.setFont(font)
        self.pb_Tambah.setObjectName("pb_Tambah")
        self.pb_Tambah.clicked.connect(self.tambah)

        self.horizontalLayout_3.addWidget(self.pb_Tambah)
        self.pb_kurang = QtWidgets.QPushButton(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.pb_kurang.setFont(font)
        self.pb_kurang.setObjectName("pb_kurang")
        self.pb_kurang.clicked.connect(self.kurang)

        self.horizontalLayout_3.addWidget(self.pb_kurang)
        self.pb_kali = QtWidgets.QPushButton(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.pb_kali.setFont(font)
        self.pb_kali.setObjectName("pb_kali")
        self.pb_kali.clicked.connect(self.kali)

        self.horizontalLayout_3.addWidget(self.pb_kali)
        self.pb_bagi = QtWidgets.QPushButton(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.pb_bagi.setFont(font)
        self.pb_bagi.setObjectName("pb_bagi")
        self.pb_bagi.clicked.connect(self.bagi)

        self.horizontalLayout_3.addWidget(self.pb_bagi)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem3 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.lbl_hasil = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.lbl_hasil.setFont(font)
        self.lbl_hasil.setStyleSheet("QLable{\n"
                                     "color:green\n"
                                     "}")
        self.lbl_hasil.setText("")
        self.lbl_hasil.setObjectName("lbl_hasil")
        self.verticalLayout.addWidget(self.lbl_hasil)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def tambah(self):
        angkaP = int(self.lineEditPertama.text())
        angkaK = int(self.lineEditKedua.text())
        hasil = angkaP+angkaK
        self.lbl_hasil.setText("Penambahan : {} ".format(hasil))

    def kurang(self):
        angkaP = int(self.lineEditPertama.text())
        angkaK = int(self.lineEditKedua.text())
        hasil = angkaP-angkaK
        self.lbl_hasil.setText("Pengurangan : {} ".format(hasil))

    def kali(self):
        angkaP = int(self.lineEditPertama.text())
        angkaK = int(self.lineEditKedua.text())
        hasil = angkaP*angkaK
        self.lbl_hasil.setText("Perkalian : {} ".format(hasil))

    def bagi(self):
        angkaP = int(self.lineEditPertama.text())
        angkaK = int(self.lineEditKedua.text())
        hasil = angkaP/angkaK
        self.lbl_hasil.setText("Perbagian : {} ".format(hasil))

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Kalkulator"))
        self.label.setText(_translate("Form", "Angka Pertama"))
        self.lineEditPertama.setPlaceholderText(
            _translate("Form", "Masukkan angka pertama"))
        self.label_2.setText(_translate("Form", "Angka Kedua"))
        self.lineEditKedua.setPlaceholderText(
            _translate("Form", "Masukkan Angka Kedua"))
        self.pb_Tambah.setText(_translate("Form", "+"))
        self.pb_kurang.setText(_translate("Form", "-"))
        self.pb_kali.setText(_translate("Form", "X"))
        self.pb_bagi.setText(_translate("Form", "/"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
