# Form implementation generated from reading ui file 'flight_dmeo.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QDialog


class Ui_Dialog(QDialog):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        Dialog.setStyleSheet("QDialog{\n"
                             "background-color:yellow\n"
                             "}\n"
                             "QLabel{\n"
                             "color:green\n"
                             "}")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_1 = QtWidgets.QRadioButton(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.radioButton_1.setFont(font)
        self.radioButton_1.setObjectName("radioButton_1")
        self.verticalLayout.addWidget(self.radioButton_1)
        self.radioButton_1.toggled.connect(self.radio_selected)

        self.radioButton_2 = QtWidgets.QRadioButton(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout.addWidget(self.radioButton_2)
        self.radioButton_2.toggled.connect(self.radio_selected)

        self.radioButton_3 = QtWidgets.QRadioButton(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_3.toggled.connect(self.radio_selected)

        self.verticalLayout.addWidget(self.radioButton_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.lbl_hasil = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.lbl_hasil.setFont(font)
        self.lbl_hasil.setObjectName("lbl_hasil")
        self.verticalLayout_2.addWidget(self.lbl_hasil)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def radio_selected(self):
        radio_btn = self.sender()
        if radio_btn.isChecked():
            self.lbl_hasil.setText(f"Anda memilih:  {radio_btn.text()}")

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Select Flight Type"))
        self.radioButton_1.setText(_translate("Dialog", "First Class   150"))
        self.radioButton_2.setText(_translate(
            "Dialog", "Business Class   120"))
        self.radioButton_3.setText(_translate(
            "Dialog", "Economic Class   100"))
        self.lbl_hasil.setText(_translate("Dialog", ""))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
